# Generated by Django 4.2.4 on 2023-08-18 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='src',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('f7cad7aa-a70f-4e63-b13b-e08e3b4be8c1'), primary_key=True, serialize=False),
        ),
    ]
