# Generated by Django 4.2.4 on 2023-08-21 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_src_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('38ffb389-ee33-45e7-a42a-0455e2716af9'), primary_key=True, serialize=False),
        ),
    ]
