# Generated by Django 4.2.4 on 2023-08-21 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_src_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('256424d2-5b81-46c6-b56e-809115ec0081'), primary_key=True, serialize=False),
        ),
    ]
