# Generated by Django 4.2.4 on 2023-08-21 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('31518158-1673-49c0-bdc0-6d80bc5f97df'), primary_key=True, serialize=False),
        ),
    ]
