# Generated by Django 4.2.4 on 2023-08-21 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('9bd691c0-3fd2-44cd-8a92-4e19bffcbfdc'), primary_key=True, serialize=False),
        ),
    ]
