# Generated by Django 4.2.4 on 2023-08-21 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.TextField(default=uuid.UUID('286ed0db-a618-4c80-8a26-db9908711c8e'), primary_key=True, serialize=False),
        ),
    ]
