# Generated by Django 4.2.4 on 2023-10-04 17:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(null=True, upload_to=api.models.video_path),
        ),
    ]
