# Generated by Django 4.2.4 on 2023-10-11 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_video_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(upload_to=api.models.video_path),
        ),
    ]
