# Generated by Django 4.2.4 on 2023-10-12 09:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_video_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(null=True, upload_to=api.models.video_path),
        ),
    ]
