# Generated by Django 4.2.4 on 2023-10-17 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_video_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('iid', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('question', models.TextField(null=True)),
                ('answer1', models.TextField(null=True)),
                ('answer2', models.TextField(null=True)),
                ('answer3', models.TextField(null=True)),
                ('answer4', models.TextField(null=True)),
                ('realAnswer', models.TextField(null=True)),
                ('videoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
